language: node_js
env:
  global:
    - TRAVIS_BUILD_DIR = "web-ng"
install:
  - npm install
script:
  - npm run test
before_install:
  - npm install codecov -g
after_success:
  - npm run test
  - codecov --token=secrets.CODECOV_TOKEN -f coverage/*.json
