# Initialize gcloud via CLI
# $ gcloud init

steps:

  # Install node packages for firestore
  - name: 'gcr.io/cloud-builders/npm'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       cd firestore && npm install

  # Install node packages for functions
  - name: 'gcr.io/cloud-builders/npm'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       cd functions && npm install

  # Install node packages for web
  - name: 'gcr.io/cloud-builders/npm'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       cd web && npm install

  # Install node packages for web-ng
  - name: 'gcr.io/cloud-builders/npm'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       cd web-ng && npm install

  # Run eslint for web-ng
  - name: 'gcr.io/cloud-builders/npm'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       cd web-ng && npm run eslint
