# Initialize gcloud via CLI
# $ gcloud init

steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args:
     - '-c'
     - |
       cd functions && npm install

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]
